- Generating random numbers using numpys random module

In [3]:
import numpy as np
import pandas as pd
np.random.seed(31)

- np.random.choice: selects random options from a list.
- arguments for random.choice(a, size=None, replace=True, p=None)

    - a = 1-D array like or int
    - size : int or tuple of ints, optional
    - p : 1-D array-like, optional. The probabilities associated with each entry in a.
    

In [20]:
np.random.choice([1,2,3,4,5], size = 4, p= [1/8,1/4, 1/4, 1/8, 1/4])

array([3, 4, 1, 2])

In [28]:
# simulating a dice roll using the random.choice
sides = [1,2,3,4,5,6]
size = 3 # number of times you are rolling
p = [1/6,1/6,1/6,1/6,1/6,1/6]
results = np.random.choice(sides, size, p)
results

array([2, 5, 6])

- lets say we are rolling 2 dice, how likely that we roll doubles?
    - we can use the random.choice to answer this question

In [52]:
sides = [1,2,3,4,5,6]
number_of_dice = 2

# lets say we want to roll it 100,000 times to get the actual probability of rolling doubles so,

size = 100_000
# we know the probability to be
p = [1/6,1/6,1/6,1/6,1/6,1/6] 

# also, the p argument is optional, if you dont provide anything, it will default to equal probability for all the value
results = np.random.choice(sides, size * number_of_dice, p).reshape(size, number_of_dice)
results

# solving this problem using a good ole fashion loop
count = 0
for result in results:
    if result[0]==result[1]:
        count += 1
probability = count/size
probability

0.16648

In [53]:
# use of just numpy to solve the above problem

a = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
b = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
(a==b).mean()



0.16523

In [54]:
# we can solve this problem using panda DataFrame
results = pd.DataFrame(results)
(results[0]==results[1]).mean()

0.16648

- np.random.uniform: generates numbers between a given lower and upper bound

In [57]:
my_numbers = np.random.uniform(1,5,5)
my_numbers

array([1.70694996, 4.56582616, 2.91273439, 2.92087902, 4.24727223])

- np.random.uniform(low=0.0, high=1.0, size=None)

- Draw samples from a uniform distribution.
- uniform distribution means, every element has equal likelihood of occuring

In [64]:
numbers= np.random.uniform(1,5,10)
# we are selecting 10 numbers that are uniformly distributed between 1 and 5
numbers

array([3.73591673, 4.25508553, 3.87199811, 1.79464984, 1.49760243,
       2.44128834, 2.1608015 , 2.97921628, 4.84297814, 2.38755861])

- np.random.random: generates numbers between 0 and 1
- Return random floats in the half-open interval [0.0, 1.0)
- np.random.random(size=None)

In [67]:
x = np.random.random(10)
x

array([0.74432808, 0.52390843, 0.06065989, 0.16001208, 0.4133807 ,
       0.73846465, 0.95596594, 0.36818055, 0.96372533, 0.13938102])

- np.random.randn: generates numbers from the standard normal distribution
- standard normal distribution is signified by mean of 0 and a standard deviation of 1
- np.random.randn(d0, d1, ..., dn)
    - d0, d1, ---, dn : int, optional. The dimensions of the returned array, must be non-negative.If no argument is given a single Python float is returned.

In [71]:
np.random.randn(2,10)

array([[-0.51408344, -0.62430831, -0.33035245, -0.28334855,  1.33914296,
         0.04079548, -1.33207859, -0.4152104 , -0.1672892 ,  0.53954601],
       [-1.66489403, -1.73306388, -1.41379627,  0.74563564, -1.00205763,
        -0.32516646,  1.83888644, -0.06434213, -0.25830156,  0.20402419]])

- np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation
- np.random.normal(loc(mean)=0.0, scale(standard deviation)=1.0, size=None)

In [79]:
np.random.normal(1,2,(4,4))
# we are getting a 4 by 4 array of numbers drawn from a normal distribution of mean 1 and sd of 2

array([[ 4.38369196, -2.90039292, -0.47453848,  0.15700906],
       [ 3.48273441,  3.39785292,  2.88301612, -1.89945202],
       [ 3.44577472,  1.33129559,  1.32682697,  0.55708305],
       [ 3.28840493,  0.65902496,  0.05011168,  2.08603967]])

In [115]:
#If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

number_of_coins = 8
choices = ['heads', 'tails']
probability = [1/2, 1/2]
size = 100_000
results = np.random.choice(choices, size * number_of_coins, probability).reshape(size, number_of_coins)
results = pd.DataFrame(results)
((results == 'heads').sum(axis = 1) == 3).mean() # probability of getting exactly three heads



0.21893

In [116]:
# probability of getting more than 3 heads

((results == 'heads').sum(axis = 1) > 3).mean()

0.6348

In [137]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two 
#billboards I drive past both have data science students on them?

probability = [0.75, 0.25]
choices = ['webdev', 'datas']
results = np.random.choice(choices, 2* 100_000, probability).reshape(100_000, 2)
results = pd.DataFrame(results)
((results=='datas').sum(axis = 1) == 2).mean()

0.2478

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [142]:
avg = 3
std = 1.5
total = 17
results = np.random.normal(avg, std, 5 * 100_000).reshape(100_000, 5)
(results.sum(axis = 1) < 17).mean()

0.72698